server:
  port: 8000

spring:
  application:
    name: sportcenter
  datasource:
    url: jdbc:mysql://localhost:3306/sport-center
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
