server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_USERNAME:root}:${DB_PASSWORD:password}@${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sports-center}?ssl-mode=REQUIRED
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  application:
    name: SportsCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
